### ISSUE TITLE
Loading icon while page is loading

### ISSUE THREAD

**Issue by paintedstork** [birdatlaskerala/atlas#1]
Some phones on the edge network takes while before all the excel files are loaded by the browser. Is it a good idea to show a loading icon based on the snippet in this link? 

http://smallenvelop.com/display-loading-icon-page-loads-completely/

Would this code be OK with the variants of mobiles/OS ?

**Comment by birdatlaskerala** [comment]
I'm glad and mildly surprised that it works on Edge. There are a number of scripts and maps itself it heavy on n/w usage.

Tabs are loaded when they are selected and the data is not fetched again unless page itself is refreshed, so that helps. 

Will see how a spinner can be added.

**Comment by birdatlaskerala** [comment]
Added loading image to map tabs.

**Comment by paintedstork** [comment]
Checked in my edge.. Is working... Thank you
