### ISSUE TITLE
Download cluster polygons along with sub-cells

### ISSUE THREAD

**Issue by paintedstork** [birdatlaskerala/atlas#10]
There is a download option available in this site. Is it possible to also download the polygons created for the cluster along with the sub-cells ?

**Comment by birdatlaskerala** [comment]
Clusters are also polygons like sub-cells. So it should be possible.

**Comment by paintedstork** [comment]
It would be great if you could enable this sometime when you have some time free. 
Single download button, but if clusters are enabled, then download clusters polygons also.
If downloading clusters ALWAYS is simpler, that is also fine.

**Comment by birdatlaskerala** [comment]
Enabled cluster display in KML export.
