### ISSUE TITLE
Support Cluster Visualisation

### ISSUE THREAD

**Issue by paintedstork** [birdatlaskerala/atlas#3]
A cluster is a set of sub-cells with the "Cluster" column in planning sheet. Creating a semi-transparent overlay over all sub-cells with cluster name would help some districts. Now they are hand-drawing. 

What is required is a "Bounding Polygon" for all points in the sub-cells with cluster name = "X". Add a 10% opacity and a colour to the polygon and name of the cluster. 

Is there an existing script for Bounding Box in JS or do we need to implement it ourselves ?

**Comment by birdatlaskerala** [comment]
It is possible, but will have to do it ourselves. The issue is, there might be overlaps at the edges depending on how the cluster nodes are setup. If that is ok, looks like it can be done relatively easily.

**Comment by paintedstork** [comment]
Overlap is ok..as we will pick a different base color for each cluster.

**Comment by birdatlaskerala** [comment]
Does this look about right?

![image](https://cloud.githubusercontent.com/assets/16912372/17048839/9f97849c-5006-11e6-9edd-f96aadbeb6e8.png)

![image](https://cloud.githubusercontent.com/assets/16912372/17048891/fd401d66-5006-11e6-9d39-59af041d30bc.png)

![image](https://cloud.githubusercontent.com/assets/16912372/17048905/0f8a84f2-5007-11e6-843e-a5875fee4ab8.png)

![image](https://cloud.githubusercontent.com/assets/16912372/17048911/19fc9fba-5007-11e6-84d3-d14789cd36de.png)

**Comment by paintedstork** [comment]
This is awesome - just one small change if you can, can you suppress any
cluster which is marked "F" - across all districts...

thanks & best rgds
Praveen

**Comment by birdatlaskerala** [comment]
In Palakkad, there are cells with cluster name TCR. And when we draw around them, other cells also end up within that polygon.

![image](https://cloud.githubusercontent.com/assets/16912372/17049382/af421f70-500a-11e6-8768-96c9d6f43e81.png)

**Comment by paintedstork** [comment]
That I ve means to handle, by retaining them to geographical nearest ones...

**Comment by paintedstork** [comment]
_renaming_
