### ISSUE TITLE
Current Location tracker

### ISSUE THREAD

**Issue by birdatlaskerala** [birdatlaskerala/atlas#4]
On supporting devices/browsers, enable display of the current location of the device.

**Comment by birdatlaskerala** [comment]
@paintedstork 
Featured pushed to repository. Submit issues, if users face any problem. 
On chrome the features is supported only for the secure url. https://birdatlaskerala.github.io/atlas/

**Comment by paintedstork** [comment]
Sorry for asking, what is this feature?

**Comment by birdatlaskerala** [comment]
The blue circle is the current location. Use the circle button on the menu to show the current location. Clicking on the flag button re-centers the map.

![img_2727](https://cloud.githubusercontent.com/assets/16912372/17428935/6c181d6c-5b09-11e6-8444-57781f8c36aa.PNG)

**Comment by paintedstork** [comment]
Okie thank you - they use Google Maps, GPSViewer & Locus Free for
navigation...

thanks & best rgds
Praveen
